// Shared vehicle data - this would typically come from a database or CMS
export const vehicles = {
  "toyota-wigo-at-2025-silver": {
    id: "toyota-wigo-at-2025-silver",
    name: "Toyota Wigo AT 2025",
    category: "Hatchback",
    images: ["/vehicles/Toyota Wigo AT 2025.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 4,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱1,800",
    pricePer12hr: "₱1,500",
    rating: 4.8,
    reviews: 45,
    description:
      "The Toyota Wigo AT 2025 is the perfect compact car for city driving and short trips around Bicol. With its ultra-fuel-efficient engine and easy-to-park design, it's ideal for solo travelers or couples exploring the region's attractions.",
    features: [
      "Ultra Fuel Efficient",
      "Compact City Design",
      "Easy Parking",
      "Air Conditioning",
      "Power Steering",
      "Automatic Transmission",
      "Modern Dashboard",
      "USB Charging Port",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.0L 3-Cylinder",
      fuelCapacity: "35 Liters",
      luggage: "1-2 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Wigo",
    year: "2025",
    color: "Silver",
    colors: ["Silver", "Orange"],
    popular: false,
  },
  "toyota-wigo-mt-2019-orange": {
    id: "toyota-wigo-mt-2019-orange",
    name: "Toyota Wigo MT 2019",
    category: "Hatchback",
    images: ["/vehicles/Toyota Wigo MT 2019 Orange.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 4,
    transmission: "Manual",
    fuel: "Gasoline",
    pricePerDay: "₱1,800",
    pricePer12hr: "₱1,500",
    rating: 4.7,
    reviews: 38,
    description:
      "The Toyota Wigo MT 2019 offers excellent value for budget-conscious travelers. With its manual transmission and fuel-efficient engine, it's perfect for those who prefer more control over their driving experience.",
    features: [
      "Budget Friendly",
      "Compact Design",
      "Easy Parking",
      "Air Conditioning",
      "Manual Control",
      "Fuel Efficient",
      "Reliable Engine",
      "Simple Dashboard",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.0L 3-Cylinder",
      fuelCapacity: "35 Liters",
      luggage: "1-2 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Wigo",
    year: "2019",
    color: "Orange",
    colors: ["Orange", "White", "Silver"],
    popular: false,
  },
  "toyota-vios-at-2025-blackish-red": {
    id: "toyota-vios-at-2025-blackish-red",
    name: "Toyota Vios AT 2025",
    category: "Sedan",
    images: ["/vehicles/Toyota Vios AT 2025 Blackish Red.webp", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.9,
    reviews: 124,
    description:
      "The Toyota Vios AT 2025 is perfect for city driving and short trips around Bicol. With its fuel-efficient engine and comfortable interior, it's ideal for couples or small families exploring the region.",
    features: [
      "Modern Interior",
      "Bluetooth Connectivity",
      "Safety Features",
      "Air Conditioning",
      "GPS Navigation",
      "Automatic Transmission",
      "Premium Audio System",
      "Keyless Entry",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.3L 4-Cylinder",
      fuelCapacity: "42 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Vios",
    year: "2025",
    color: "Blackish Red",
    colors: ["Blackish Red", "Super Red", "Blue", "Silver"],
    popular: true,
  },
  "toyota-vios-at-2025-super-red": {
    id: "toyota-vios-at-2025-super-red",
    name: "Toyota Vios AT 2025",
    category: "Sedan",
    images: ["/vehicles/Toyota Vios AT 2025 Super Red.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.9,
    reviews: 124,
    description:
      "The Toyota Vios AT 2025 is perfect for city driving and short trips around Bicol. With its fuel-efficient engine and comfortable interior, it's ideal for couples or small families exploring the region.",
    features: [
      "Modern Interior",
      "Bluetooth Connectivity",
      "Safety Features",
      "Air Conditioning",
      "GPS Navigation",
      "Automatic Transmission",
      "Premium Audio System",
      "Keyless Entry",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.3L 4-Cylinder",
      fuelCapacity: "42 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Vios",
    year: "2025",
    color: "Super Red",
    colors: ["Blackish Red", "Super Red", "Blue", "Silver"],
    popular: true,
  },
  "toyota-vios-at-2025-blue": {
    id: "toyota-vios-at-2025-blue",
    name: "Toyota Vios AT 2025",
    category: "Sedan",
    images: ["/vehicles/Toyota Vios AT 2025 Blue.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.9,
    reviews: 124,
    description:
      "The Toyota Vios AT 2025 is perfect for city driving and short trips around Bicol. With its fuel-efficient engine and comfortable interior, it's ideal for couples or small families exploring the region.",
    features: [
      "Modern Interior",
      "Bluetooth Connectivity",
      "Safety Features",
      "Air Conditioning",
      "GPS Navigation",
      "Automatic Transmission",
      "Premium Audio System",
      "Keyless Entry",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.3L 4-Cylinder",
      fuelCapacity: "42 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Vios",
    year: "2025",
    color: "Blue",
    colors: ["Blackish Red", "Super Red", "Blue", "Silver"],
    popular: true,
  },
  "toyota-vios-at-2025-silver": {
    id: "toyota-vios-at-2025-silver",
    name: "Toyota Vios AT 2025",
    category: "Sedan",
    images: ["/vehicles/Toyota Vios AT 2025 Silver.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.9,
    reviews: 124,
    description:
      "The Toyota Vios AT 2025 is perfect for city driving and short trips around Bicol. With its fuel-efficient engine and comfortable interior, it's ideal for couples or small families exploring the region.",
    features: [
      "Modern Interior",
      "Bluetooth Connectivity",
      "Safety Features",
      "Air Conditioning",
      "GPS Navigation",
      "Automatic Transmission",
      "Premium Audio System",
      "Keyless Entry",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.3L 4-Cylinder",
      fuelCapacity: "42 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Vios",
    year: "2025",
    color: "Silver",
    colors: ["Blackish Red", "Super Red", "Blue", "Silver"],
    popular: true,
  },
  "toyota-vios-at-2026-silver": {
    id: "toyota-vios-at-2026-silver",
    name: "Toyota Vios AT 2026",
    category: "Sedan",
    images: ["/vehicles/Toyota Vios AT 2025 Silver.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.9,
    reviews: 67,
    description:
      "The latest Toyota Vios AT 2026 features the most advanced technology and safety features. Perfect for those who want the newest model with premium amenities for their Bicol adventure.",
    features: [
      "Latest Model",
      "Premium Interior",
      "Advanced Safety",
      "Bluetooth Audio",
      "USB Charging",
      "Touchscreen Display",
      "Backup Camera",
      "Lane Departure Warning",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.3L 4-Cylinder",
      fuelCapacity: "42 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Automatic A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Vios",
    year: "2026",
    color: "Silver",
    colors: ["Silver"],
    popular: true,
  },
  "toyota-avanza-at-2023-silver": {
    id: "toyota-avanza-at-2023-silver",
    name: "Toyota Avanza AT 2023",
    category: "SUV",
    images: ["/vehicles/Toyota Avanza AT 2023 Silver.webp", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 7,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱3,000",
    pricePer12hr: "₱2,500",
    rating: 4.8,
    reviews: 89,
    description:
      "The Toyota Avanza AT 2023 is perfect for larger groups and families. With its 7-seat capacity and spacious interior, it's ideal for group tours and family adventures around Bicol.",
    features: [
      "7-Seat Capacity",
      "Spacious Interior",
      "USB Charging",
      "Luggage Space",
      "Air Conditioning",
      "Automatic Transmission",
      "Power Windows",
      "Central Locking",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.5L 4-Cylinder",
      fuelCapacity: "45 Liters",
      luggage: "3-4 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Avanza",
    year: "2023",
    color: "Silver",
    colors: ["Silver", "White", "Black"],
    popular: false,
  },
  "toyota-avanza-mt-2024-black": {
    id: "toyota-avanza-mt-2024-black",
    name: "Toyota Avanza MT 2024",
    category: "SUV",
    images: ["/vehicles/Toyota Avanza MT 2024 Black.png", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 7,
    transmission: "Manual",
    fuel: "Gasoline",
    pricePerDay: "₱3,000",
    pricePer12hr: "₱2,500",
    rating: 4.7,
    reviews: 56,
    description:
      "The Toyota Avanza MT 2024 offers the same spacious 7-seat capacity with manual transmission for those who prefer more control. Perfect for group trips and family outings.",
    features: [
      "7-Seat Capacity",
      "Spacious Interior",
      "Manual Transmission",
      "Luggage Space",
      "Air Conditioning",
      "Power Steering",
      "Power Windows",
      "Central Locking",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.5L 4-Cylinder",
      fuelCapacity: "45 Liters",
      luggage: "3-4 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Avanza",
    year: "2024",
    color: "Black",
    colors: ["Black"],
    popular: false,
  },
  "toyota-rush-at-2025-white": {
    id: "toyota-rush-at-2025-white",
    name: "Toyota Rush AT 2025",
    category: "SUV",
    images: ["/vehicles/Toyota Rush AT 2025 White.webp", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 7,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱3,000",
    pricePer12hr: "₱2,500",
    rating: 4.8,
    reviews: 73,
    description:
      "The Toyota Rush AT 2025 combines SUV capability with city-friendly features. With 4WD capability and premium interior, it's perfect for both city driving and light off-road adventures in Bicol.",
    features: [
      "4WD Capability",
      "Premium Interior",
      "Advanced Safety",
      "Hill Assist",
      "7-Seat SUV",
      "Automatic Transmission",
      "Touchscreen Display",
      "Backup Camera",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.5L 4-Cylinder",
      fuelCapacity: "45 Liters",
      luggage: "3-4 Large Bags",
      doors: 4,
      aircon: "Automatic A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Rush",
    year: "2025",
    color: "White",
    colors: ["White"],
    popular: false,
  },
  "toyota-innova-at-2024-white": {
    id: "toyota-innova-at-2024-white",
    name: "Toyota Innova AT 2024",
    category: "SUV",
    images: ["/vehicles/Toyota Innova AT 2024 White.webp", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 8,
    transmission: "Automatic",
    fuel: "Diesel",
    pricePerDay: "₱3,500",
    pricePer12hr: "₱3,000",
    rating: 4.9,
    reviews: 156,
    description:
      "The Toyota Innova AT 2024 is our most popular family vehicle, offering spacious seating for up to 8 passengers. Perfect for family trips, group tours, and airport transfers with ample luggage space.",
    features: [
      "8-Seat Capacity",
      "Diesel Engine",
      "Spacious Interior",
      "USB Charging",
      "Luggage Space",
      "Automatic Transmission",
      "Premium Audio",
      "Climate Control",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "2.5L Diesel",
      fuelCapacity: "55 Liters",
      luggage: "4-6 Large Bags",
      doors: 4,
      aircon: "Automatic A/C",
    },
    type: "Self Drive",
    brand: "Toyota",
    model: "Innova",
    year: "2024",
    color: "White",
    colors: ["White"],
    popular: true,
  },
  "mitsubishi-xpander-at-2024-white": {
    id: "mitsubishi-xpander-at-2024-white",
    name: "Mitsubishi Xpander AT 2024",
    category: "SUV",
    images: ["/vehicles/Mitsubishi Xpander AT 2024 White.png", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 7,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱3,000",
    pricePer12hr: "₱2,500",
    rating: 4.7,
    reviews: 92,
    description:
      "The Mitsubishi Xpander AT 2024 offers modern design and spacious 7-seat capacity. Perfect for families and groups looking for a stylish and comfortable ride around Bicol.",
    features: [
      "7-Seat Capacity",
      "Modern Design",
      "Safety Features",
      "Air Conditioning",
      "Spacious Interior",
      "Automatic Transmission",
      "Touchscreen Display",
      "USB Charging",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.5L 4-Cylinder",
      fuelCapacity: "45 Liters",
      luggage: "3-4 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Mitsubishi",
    model: "Xpander",
    year: "2024",
    color: "White",
    colors: ["White"],
    popular: false,
  },
  "nissan-navara-4x4-at-2025-gray": {
    id: "nissan-navara-4x4-at-2025-gray",
    name: "Nissan Navara 4×4 AT 2025",
    category: "Pickup",
    images: ["/vehicles/Nissan Navara 4x4 AT 2025 Gray.png", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Diesel",
    pricePerDay: "₱4,000",
    pricePer12hr: "₱3,500",
    rating: 4.8,
    reviews: 67,
    description:
      "The Nissan Navara 4×4 AT 2025 is perfect for adventure seekers and those who need power and clearance. With its 4WD capability and robust build, it's ideal for off-road adventures and heavy-duty tasks.",
    features: [
      "4WD Capability",
      "Powerful Diesel Engine",
      "High Ground Clearance",
      "Tough Build",
      "Automatic Transmission",
      "Advanced Safety",
      "Touchscreen Display",
      "Backup Camera",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "2.5L Diesel",
      fuelCapacity: "80 Liters",
      luggage: "Large Cargo Bed",
      doors: 4,
      aircon: "Automatic A/C",
    },
    type: "Self Drive",
    brand: "Nissan",
    model: "Navara",
    year: "2025",
    color: "Gray",
    colors: ["Gray"],
    popular: false,
  },
  "mitsubishi-mirage-g4-at-2024-red": {
    id: "mitsubishi-mirage-g4-at-2024-red",
    name: "Mitsubishi Mirage G4 AT 2024",
    category: "Sedan",
    images: ["/vehicles/Mitsubishi Mirage G4 AT 2024 Red.png", "/toyota-vios-interior.jpg", "/toyota-vios-dashboard.jpg"],
    seats: 5,
    transmission: "Automatic",
    fuel: "Gasoline",
    pricePerDay: "₱2,000",
    pricePer12hr: "₱1,500",
    rating: 4.6,
    reviews: 34,
    description:
      "The Mitsubishi Mirage G4 AT 2024 is a fuel-efficient sedan perfect for city driving and short trips. With its compact design and modern interior, it's ideal for couples or small families.",
    features: [
      "Fuel Efficient",
      "Compact Design",
      "Air Conditioning",
      "Modern Interior",
      "Automatic Transmission",
      "Power Steering",
      "USB Charging",
      "Bluetooth Audio",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees", "Driver (Self-Drive Only)"],
    specifications: {
      engine: "1.2L 3-Cylinder",
      fuelCapacity: "35 Liters",
      luggage: "2-3 Large Bags",
      doors: 4,
      aircon: "Manual A/C",
    },
    type: "Self Drive",
    brand: "Mitsubishi",
    model: "Mirage G4",
    year: "2024",
    color: "Red",
    colors: ["Red"],
    popular: false,
  },
  "l300-carry-mt-2024-white": {
    id: "l300-carry-mt-2024-white",
    name: "L300 Carry MT 2024",
    category: "Van",
    images: ["/vehicles/L300 Carry MT 2024 White.png", "/toyota-innova-interior-spacious.jpg", "/toyota-innova-luggage-space.jpg"],
    seats: 12,
    transmission: "Manual",
    fuel: "Diesel",
    pricePerDay: "₱3,000",
    pricePer12hr: "₱2,500",
    rating: 4.5,
    reviews: 28,
    description:
      "The L300 Carry MT 2024 is perfect for large groups and cargo transport. With its 12-seat capacity and large cargo space, it's ideal for group tours, airport transfers, and cargo delivery services.",
    features: [
      "12-Seat Capacity",
      "Large Cargo Space",
      "Durable Design",
      "Power Steering",
      "Diesel Engine",
      "Manual Transmission",
      "High Ground Clearance",
      "Robust Build",
    ],
    inclusions: [
      "Comprehensive Insurance",
      "24/7 Roadside Assistance",
      "Free Delivery (Legazpi/Naga)",
      "Unlimited Mileage",
      "Basic Maintenance",
      "Professional Driver",
    ],
    exclusions: ["Fuel", "Toll Fees", "Parking Fees"],
    specifications: {
      engine: "2.5L Diesel",
      fuelCapacity: "60 Liters",
      luggage: "Large Cargo Space",
      doors: 2,
      aircon: "Manual A/C",
    },
    type: "With Driver",
    brand: "Mitsubishi",
    model: "L300 Carry",
    year: "2024",
    color: "White",
    colors: ["White"],
    popular: false,
  },
} as const

export type Vehicle = typeof vehicles[keyof typeof vehicles]

// Helper function to get all vehicles as an array
export function getAllVehicles(): Vehicle[] {
  return Object.values(vehicles)
}

// Helper function to get a vehicle by ID
export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles[id as keyof typeof vehicles]
}

// Helper function to get vehicle IDs for static generation
export function getVehicleIds(): string[] {
  return Object.keys(vehicles)
}
